#!/usr/bin/env python3
"""
IBKR SPY Timing Trader
======================
Executes the SPY market-timing strategy via Interactive Brokers.

Logic:
  - Reads spy_timing_signal_latest.csv (generated by 06_02_predict_spy_timing.py)
  - BUY  → Sell any non-SPY positions (e.g., IAU/gold), buy SPY with all available cash
  - CASH → Sell SPY position, hold cash

Features:
  - Fractional shares via cashQty orders (deploy ~100% of capital)
  - Staleness guard: refuses to trade on signals older than 2 calendar days
  - Minimum confidence threshold (configurable)
  - Trade logging to spy_timing_trade_log.csv
  - Optional email alerts via Gmail

Requirements:
    pip install ib_insync pandas python-dotenv

Usage:
    python ibkr_spy_timing_trader.py          # Interactive mode
    python ibkr_spy_timing_trader.py --auto   # No confirmation (for Task Scheduler)
    python ibkr_spy_timing_trader.py --paper   # Use paper trading port 7497
"""

from ib_insync import *
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
import sys
import smtplib

# Force UTF-8 output to prevent cp1252 encoding crashes under Task Scheduler
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
sys.stderr.reconfigure(encoding='utf-8', errors='replace')
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")

# ============================================================================
# CONFIGURATION
# ============================================================================

CONFIG = {
    # IBKR Connection
    'host': '127.0.0.1',
    'port': 7496,          # 7496 = Live, 7497 = Paper
    'client_id': 2,        # Use different client_id from old trader to avoid conflicts

    # Strategy Settings
    'symbol': 'SPY',               # ETF to trade
    'exchange': 'SMART',
    'currency': 'USD',
    'min_confidence_pct': 50,      # Minimum confidence % to act on signal
    'max_signal_age_bdays': 2,     # Refuse to trade on stale signals (business days, not calendar)
    'cash_reserve_dollars': 0,     # Keep $0 reserve — deploy everything
    'use_fractional_shares': True, # Use cashQty orders for fractional shares

    # Files
    'signal_file': 'spy_timing_signal_latest.csv',
    'trade_log_file': 'spy_timing_trade_log.csv',

    # Email (disabled by default — set up .env to enable)
    'send_email': False,
    'send_on_success': True,
    'send_on_failure': True,
}

# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def send_email_alert(subject, body):
    """Send email alert via Gmail"""
    if not CONFIG['send_email']:
        return
    try:
        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From'] = EMAIL_USER
        msg['To'] = EMAIL_TO
        msg.attach(MIMEText(body, 'plain'))
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(EMAIL_USER, EMAIL_PASS)
            server.send_message(msg)
        print(f"  [OK] Email sent: {subject}")
    except Exception as e:
        print(f"  [!] Email failed: {e}")


def load_signal(signal_file):
    """Load and validate the SPY timing signal"""
    if not os.path.exists(signal_file):
        raise FileNotFoundError(f"Signal file not found: {signal_file}")

    df = pd.read_csv(signal_file)
    if len(df) == 0:
        raise ValueError("Signal file is empty")

    row = df.iloc[0]

    signal = {
        'signal_date': str(row['signal_date']),
        'execute_at': str(row.get('execute_at', 'NEXT_OPEN')),
        'signal': str(row['signal']).upper(),
        'ensemble_prob': float(row['ensemble_prob']),
        'confidence_pct': float(row['confidence_pct']),
        'generated_at': str(row.get('generated_at', '')),
    }

    # Validate signal value
    if signal['signal'] not in ('BUY', 'CASH'):
        raise ValueError(f"Invalid signal: {signal['signal']} (expected BUY or CASH)")

    return signal


def check_signal_freshness(signal, max_age_bdays):
    """Ensure the signal is not stale (using business days to handle weekends)"""
    try:
        signal_date = pd.to_datetime(signal['signal_date'])
        now = pd.Timestamp.now()
        # Count business days between signal and now
        bday_age = len(pd.bdate_range(signal_date, now)) - 1  # subtract 1 since range is inclusive
        calendar_age = (now - signal_date).days
        if bday_age > max_age_bdays:
            raise ValueError(
                f"Signal is {bday_age} business days old ({calendar_age} calendar days, "
                f"signal_date={signal['signal_date']}). "
                f"Maximum allowed: {max_age_bdays} business days. Run the prediction pipeline first."
            )
        return bday_age
    except Exception as e:
        if 'Signal is' in str(e):
            raise
        print(f"  [!] Could not parse signal_date: {signal['signal_date']}. Proceeding anyway.")
        return -1


# ============================================================================
# SPY TIMING TRADER CLASS
# ============================================================================

class SPYTimingTrader:
    """Simple trader: BUY SPY or hold CASH based on timing signal"""

    def __init__(self, config):
        self.config = config
        self.ib = IB()
        self.available_cash = 0
        self.net_liquidation = 0
        self.current_positions = []
        self.spy_position = None
        self.non_spy_positions = []
        self.trade_result = None

    # ------------------------------------------------------------------
    # Connection
    # ------------------------------------------------------------------
    def connect(self):
        """Connect to IBKR TWS/Gateway"""
        print(f"\n{'='*70}")
        print("CONNECTING TO IBKR")
        print(f"{'='*70}")

        self.ib.connect(
            self.config['host'],
            self.config['port'],
            clientId=self.config['client_id']
        )
        print(f"  [OK] Connected (port {self.config['port']})")

        # Get account summary
        summary = {e.tag: float(e.value) for e in self.ib.accountSummary()
                    if e.tag in ('AvailableFunds', 'NetLiquidation', 'TotalCashValue')}

        self.available_cash = summary.get('AvailableFunds', 0)
        self.net_liquidation = summary.get('NetLiquidation', 0)

        print(f"  [OK] Net Liquidation:  ${self.net_liquidation:,.2f}")
        print(f"  [OK] Available Cash:   ${self.available_cash:,.2f}")

    # ------------------------------------------------------------------
    # Position Scanning
    # ------------------------------------------------------------------
    def scan_positions(self):
        """Identify current SPY and non-SPY positions"""
        print(f"\n{'='*70}")
        print("SCANNING POSITIONS")
        print(f"{'='*70}")

        self.current_positions = self.ib.positions()
        self.spy_position = None
        self.non_spy_positions = []

        if not self.current_positions:
            print("  [OK] No existing positions")
            return

        for pos in self.current_positions:
            symbol = pos.contract.symbol
            qty = pos.position
            avg_cost = pos.avgCost
            mkt_value = qty * avg_cost  # approximate

            if symbol == self.config['symbol']:
                self.spy_position = pos
                print(f"  [SPY] {qty:.4f} shares @ ${avg_cost:.2f} (~${mkt_value:,.2f})")
            else:
                self.non_spy_positions.append(pos)
                print(f"  [OTHER] {symbol}: {qty:.4f} shares @ ${avg_cost:.2f}")

    # ------------------------------------------------------------------
    # Sell Helpers
    # ------------------------------------------------------------------
    def sell_position(self, position, reason=""):
        """Sell an entire position (handles fractional quantities)"""
        symbol = position.contract.symbol
        qty = abs(position.position)

        if qty <= 0:
            return True

        print(f"\n  Selling {symbol} ({qty:.4f} shares) — {reason}")

        try:
            contract = Stock(symbol, 'SMART', 'USD')
            self.ib.qualifyContracts(contract)

            order = MarketOrder('SELL', qty)
            trade = self.ib.placeOrder(contract, order)

            # Wait for fill (up to 30 seconds)
            for _ in range(15):
                self.ib.sleep(2)
                if trade.orderStatus.status in ('Filled', 'Cancelled', 'Inactive'):
                    break

            status = trade.orderStatus.status
            filled = trade.orderStatus.filled
            avg_price = trade.orderStatus.avgFillPrice

            if status == 'Filled':
                proceeds = filled * avg_price
                print(f"  [OK] Sold {filled:.4f} shares of {symbol} @ ${avg_price:.2f} = ${proceeds:,.2f}")
                return True
            else:
                print(f"  [!] Order status: {status} (filled {filled:.4f} of {qty:.4f})")
                return status in ('Filled', 'PreSubmitted', 'Submitted')

        except Exception as e:
            print(f"  [ERROR] Failed to sell {symbol}: {e}")
            return False

    def sell_non_spy_positions(self):
        """Sell all non-SPY positions (e.g., gold/IAU)"""
        if not self.non_spy_positions:
            print("  [OK] No non-SPY positions to sell")
            return

        print(f"\n  Selling {len(self.non_spy_positions)} non-SPY position(s)...")
        for pos in self.non_spy_positions:
            self.sell_position(pos, reason="Rotating to SPY")

        # Wait for settlement and refresh cash
        self.ib.sleep(3)
        self._refresh_cash()

    def sell_spy_position(self):
        """Sell SPY position (signal = CASH)"""
        if self.spy_position is None:
            print("  [OK] No SPY position to sell")
            return

        self.sell_position(self.spy_position, reason="Signal = CASH")
        self.spy_position = None

        self.ib.sleep(3)
        self._refresh_cash()

    # ------------------------------------------------------------------
    # Buy SPY
    # ------------------------------------------------------------------
    def buy_spy(self):
        """Buy SPY with all available cash (fractional or whole shares, with auto-fallback)"""
        self._refresh_cash()

        investable = self.available_cash - self.config['cash_reserve_dollars']
        if investable < 10:
            print(f"  [!] Not enough cash to buy SPY (${investable:.2f} available)")
            return None

        print(f"\n  Buying {self.config['symbol']} with ${investable:,.2f}...")

        contract = Stock(self.config['symbol'], self.config['exchange'], self.config['currency'])
        self.ib.qualifyContracts(contract)

        # Try cashQty (fractional) first, then fall back to whole shares if rejected
        use_cashqty = self.config['use_fractional_shares']

        if use_cashqty:
            result = self._place_buy_cashqty(contract, investable)
            if result is not None:
                return result
            # cashQty was rejected — fall back to whole shares
            print("  [!] cashQty rejected by IBKR — falling back to whole shares")

        # Whole-share order
        return self._place_buy_shares(contract, investable)

    def _place_buy_cashqty(self, contract, investable):
        """Attempt a cashQty (fractional) buy order. Returns result or None if rejected."""
        order = Order()
        order.action = 'BUY'
        order.orderType = 'MKT'
        order.cashQty = round(investable, 2)
        order.transmit = True
        print(f"  Order: MKT BUY cashQty=${investable:,.2f} (fractional)")

        try:
            trade = self.ib.placeOrder(contract, order)

            for _ in range(30):
                self.ib.sleep(2)
                if trade.orderStatus.status in ('Filled', 'Cancelled', 'Inactive'):
                    break

            status = trade.orderStatus.status
            filled = trade.orderStatus.filled
            avg_price = trade.orderStatus.avgFillPrice

            if status == 'Filled':
                cost = filled * avg_price
                print(f"  [OK] Bought {filled:.4f} shares of SPY @ ${avg_price:.2f} = ${cost:,.2f}")
                self.trade_result = {
                    'action': 'BUY',
                    'symbol': self.config['symbol'],
                    'shares': filled,
                    'price': avg_price,
                    'cost': cost,
                    'status': 'Filled',
                }
                return self.trade_result
            elif status == 'Cancelled':
                # cashQty not supported — return None to trigger fallback
                print(f"  [!] cashQty order cancelled by IBKR")
                return None
            else:
                print(f"  [!] Order status: {status} (filled {filled:.4f})")
                self.trade_result = {
                    'action': 'BUY',
                    'symbol': self.config['symbol'],
                    'shares': filled,
                    'price': avg_price,
                    'cost': filled * avg_price if avg_price else 0,
                    'status': status,
                }
                return self.trade_result

        except Exception as e:
            print(f"  [!] cashQty order error: {e}")
            return None

    def _place_buy_shares(self, contract, investable):
        """Buy whole shares of SPY with available cash."""
        price = self._get_price(contract)
        if price is None or price <= 0:
            print("  [ERROR] Cannot determine SPY price")
            return None

        shares = int(investable / price)
        if shares < 1:
            print(f"  [!] Cannot afford 1 share of SPY @ ${price:.2f} with ${investable:,.2f}")
            return None

        remainder = investable - (shares * price)
        print(f"  Order: MKT BUY {shares} shares (~${shares * price:,.2f}, ~${remainder:,.2f} uninvested)")

        try:
            order = MarketOrder('BUY', shares)
            trade = self.ib.placeOrder(contract, order)

            for _ in range(30):
                self.ib.sleep(2)
                if trade.orderStatus.status in ('Filled', 'Cancelled', 'Inactive'):
                    break

            status = trade.orderStatus.status
            filled = trade.orderStatus.filled
            avg_price = trade.orderStatus.avgFillPrice

            if status == 'Filled':
                cost = filled * avg_price
                print(f"  [OK] Bought {filled:.0f} shares of SPY @ ${avg_price:.2f} = ${cost:,.2f}")
                self.trade_result = {
                    'action': 'BUY',
                    'symbol': self.config['symbol'],
                    'shares': filled,
                    'price': avg_price,
                    'cost': cost,
                    'status': 'Filled',
                }
                return self.trade_result
            else:
                print(f"  [!] Order status: {status} (filled {filled:.0f})")
                self.trade_result = {
                    'action': 'BUY',
                    'symbol': self.config['symbol'],
                    'shares': filled,
                    'price': avg_price,
                    'cost': filled * avg_price if avg_price else 0,
                    'status': status,
                }
                return self.trade_result

        except Exception as e:
            print(f"  [ERROR] Buy order failed: {e}")
            return None

    # ------------------------------------------------------------------
    # Internal Helpers
    # ------------------------------------------------------------------
    def _refresh_cash(self):
        """Refresh available cash from account"""
        available = next(
            (e for e in self.ib.accountSummary() if e.tag == 'AvailableFunds'),
            None
        )
        if available:
            self.available_cash = float(available.value)
            print(f"  [OK] Available Cash: ${self.available_cash:,.2f}")

    def _get_price(self, contract):
        """Get current market price for a contract"""
        try:
            ticker = self.ib.reqMktData(contract, '', False, False)
            self.ib.sleep(3)

            price = None
            if ticker.last and ticker.last > 0 and ticker.last == ticker.last:
                price = ticker.last
            elif ticker.close and ticker.close > 0 and ticker.close == ticker.close:
                price = ticker.close
            elif (ticker.bid and ticker.ask and
                  ticker.bid > 0 and ticker.ask > 0 and
                  ticker.bid == ticker.bid and ticker.ask == ticker.ask):
                price = (ticker.bid + ticker.ask) / 2

            self.ib.cancelMktData(contract)
            return price

        except Exception as e:
            print(f"  [!] Price fetch error: {e}")
            return None

    # ------------------------------------------------------------------
    # Trade Logging
    # ------------------------------------------------------------------
    def save_trade_log(self, signal, action_taken):
        """Append trade result to CSV log"""
        log_entry = {
            'date': datetime.now().strftime('%Y-%m-%d'),
            'time': datetime.now().strftime('%H:%M:%S'),
            'signal_date': signal['signal_date'],
            'signal': signal['signal'],
            'confidence_pct': signal['confidence_pct'],
            'ensemble_prob': signal['ensemble_prob'],
            'action_taken': action_taken,
            'shares': self.trade_result['shares'] if self.trade_result else 0,
            'price': self.trade_result['price'] if self.trade_result else 0,
            'cost': self.trade_result['cost'] if self.trade_result else 0,
            'status': self.trade_result['status'] if self.trade_result else 'NO_TRADE',
        }

        log_df = pd.DataFrame([log_entry])
        log_path = self.config['trade_log_file']

        if os.path.exists(log_path):
            log_df.to_csv(log_path, mode='a', header=False, index=False)
        else:
            log_df.to_csv(log_path, index=False)

        print(f"  [OK] Trade logged to {log_path}")

    # ------------------------------------------------------------------
    # Disconnect
    # ------------------------------------------------------------------
    def disconnect(self):
        """Disconnect from IBKR"""
        print(f"\n{'='*70}")
        print("DISCONNECTING")
        print(f"{'='*70}")
        try:
            self.ib.disconnect()
            print("  [OK] Disconnected")
        except Exception:
            pass


# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    auto_mode = '--auto' in sys.argv
    paper_mode = '--paper' in sys.argv

    if paper_mode:
        CONFIG['port'] = 7497
        print("[!] PAPER TRADING MODE (port 7497)")

    print(f"\n{'='*70}")
    print("SPY TIMING TRADER — IBKR")
    print(f"{'='*70}")
    print(f"  Mode:   {'AUTOMATIC' if auto_mode else 'INTERACTIVE'}")
    print(f"  Port:   {CONFIG['port']} ({'Paper' if paper_mode else 'Live'})")
    print(f"  Time:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # ------------------------------------------------------------------
    # 1. Load and validate signal
    # ------------------------------------------------------------------
    print(f"\n{'='*70}")
    print("LOADING SIGNAL")
    print(f"{'='*70}")

    signal = load_signal(CONFIG['signal_file'])
    signal_age = check_signal_freshness(signal, CONFIG['max_signal_age_bdays'])

    print(f"  Signal Date:   {signal['signal_date']}")
    print(f"  Signal:        {signal['signal']}")
    print(f"  Probability:   {signal['ensemble_prob']:.4f}")
    print(f"  Confidence:    {signal['confidence_pct']:.1f}%")
    print(f"  Signal Age:    {signal_age} business day(s)")

    # Confidence check
    if signal['confidence_pct'] < CONFIG['min_confidence_pct']:
        print(f"\n  [!] Confidence {signal['confidence_pct']:.1f}% < minimum {CONFIG['min_confidence_pct']}%")
        print(f"  [!] Signal too weak — no trade executed.")
        return

    # ------------------------------------------------------------------
    # 2. Confirmation (unless --auto)
    # ------------------------------------------------------------------
    if not auto_mode:
        print(f"\n  >>> Signal: {signal['signal']} with {signal['confidence_pct']:.1f}% confidence")
        confirm = input(f"  Execute trade? (yes/no): ").strip().lower()
        if confirm != 'yes':
            print("  [X] Cancelled by user")
            return

    # ------------------------------------------------------------------
    # 3. Connect and trade
    # ------------------------------------------------------------------
    trader = SPYTimingTrader(CONFIG)

    try:
        trader.connect()
        trader.scan_positions()

        action_taken = 'NONE'

        if signal['signal'] == 'BUY':
            print(f"\n{'='*70}")
            print("ACTION: BUY SPY")
            print(f"{'='*70}")

            # Already holding SPY? Check if we need to do anything
            if trader.spy_position is not None and not trader.non_spy_positions:
                spy_qty = trader.spy_position.position
                print(f"\n  Already holding {spy_qty:.4f} shares of SPY")

                # Check if there's meaningful uninvested cash
                if trader.available_cash > 50:
                    print(f"  ${trader.available_cash:,.2f} uninvested cash — buying more SPY")
                    trader.buy_spy()
                    action_taken = 'BUY_MORE'
                else:
                    print(f"  Fully invested — no action needed")
                    action_taken = 'HOLD_SPY'

            else:
                # Sell non-SPY positions first (e.g., gold/IAU)
                if trader.non_spy_positions:
                    trader.sell_non_spy_positions()

                # Buy SPY with all available cash
                trader.buy_spy()
                action_taken = 'BUY_SPY'

        elif signal['signal'] == 'CASH':
            print(f"\n{'='*70}")
            print("ACTION: MOVE TO CASH")
            print(f"{'='*70}")

            if trader.spy_position is not None:
                trader.sell_spy_position()
                action_taken = 'SELL_SPY'
            else:
                print("\n  Already in cash — no action needed")
                action_taken = 'HOLD_CASH'

            # Also sell any other positions (shouldn't have any, but just in case)
            if trader.non_spy_positions:
                trader.sell_non_spy_positions()
                action_taken = 'SELL_ALL'

        # ------------------------------------------------------------------
        # 4. Log and report
        # ------------------------------------------------------------------
        trader.save_trade_log(signal, action_taken)

        print(f"\n{'='*70}")
        print("COMPLETED")
        print(f"{'='*70}")
        print(f"  Signal:  {signal['signal']}")
        print(f"  Action:  {action_taken}")

        if trader.trade_result:
            tr = trader.trade_result
            print(f"  Shares:  {tr['shares']:.4f}")
            print(f"  Price:   ${tr['price']:.2f}")
            print(f"  Cost:    ${tr['cost']:,.2f}")
            print(f"  Status:  {tr['status']}")

        # Email summary
        if CONFIG['send_email'] and CONFIG['send_on_success']:
            body = (
                f"SPY Timing Trade — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
                f"Signal: {signal['signal']} ({signal['confidence_pct']:.1f}% confidence)\n"
                f"Action: {action_taken}\n"
            )
            if trader.trade_result:
                body += (
                    f"Shares: {trader.trade_result['shares']:.4f}\n"
                    f"Price:  ${trader.trade_result['price']:.2f}\n"
                    f"Cost:   ${trader.trade_result['cost']:,.2f}\n"
                )
            send_email_alert(f"SPY Timing: {action_taken}", body)

    except Exception as e:
        print(f"\n  [ERROR] {e}")
        import traceback
        traceback.print_exc()

        if CONFIG['send_email'] and CONFIG['send_on_failure']:
            send_email_alert(
                "SPY Timing TRADE ERROR",
                f"Error during trade execution:\n\n{e}\n\n{traceback.format_exc()}"
            )

    finally:
        trader.disconnect()


if __name__ == "__main__":
    main()
